# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/health/db
Accept: application/json

###

POST http://127.0.0.1:8000/user
Content-Type: application/json

{
  "email": "reader@example.com",
  "username": "reader1",
  "password": "Password1"
}

###

POST http://127.0.0.1:8000/session
Content-Type: application/json

{
  "email": "reader@example.com",
  "password": "Password1"
}

###

